[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
dmandate = "8kHcaQxyxKFAK6t8KRKDUmn9FaHGZi8kwomBaSDVc4X1"

[programs.devnet]
dmandate = "8kHcaQxyxKFAK6t8KRKDUmn9FaHGZi8kwomBaSDVc4X1"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/deepanshu/solana-keypair.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
